version: '3.8'

services:
  project1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dotnet_network

networks:
  dotnet_network:

